import { ColorPalette } from "@/types/lsystem";

export const colorPalettes: ColorPalette[] = [
  {
    id: "classic",
    name: "Classic Green",
    branch: "#2d5016",
    branchDark: "#1a3010",
    leaf: "#4ade80",
    background: "#f0fdf4",
    description: "Traditional botanical green",
  },
  {
    id: "autumn",
    name: "Autumn",
    branch: "#92400e",
    branchDark: "#713f12",
    leaf: "#fb923c",
    background: "#fff7ed",
    description: "Warm autumn colors",
  },
  {
    id: "cherry-blossom",
    name: "Cherry Blossom",
    branch: "#6b3410",
    branchDark: "#4a2410",
    leaf: "#fda4af",
    background: "#fff1f2",
    description: "Spring sakura pink",
  },
  {
    id: "winter",
    name: "Winter Frost",
    branch: "#1e3a8a",
    branchDark: "#1e40af",
    leaf: "#93c5fd",
    background: "#eff6ff",
    description: "Cool winter blues",
  },
  {
    id: "sunset",
    name: "Sunset",
    branch: "#9f1239",
    branchDark: "#881337",
    leaf: "#fbbf24",
    background: "#fef3c7",
    description: "Vibrant sunset hues",
  },
  {
    id: "forest",
    name: "Deep Forest",
    branch: "#14532d",
    branchDark: "#052e16",
    leaf: "#22c55e",
    background: "#ecfdf5",
    description: "Rich forest green",
  },
  {
    id: "lavender",
    name: "Lavender Field",
    branch: "#581c87",
    branchDark: "#4c1d95",
    leaf: "#d8b4fe",
    background: "#faf5ff",
    description: "Purple lavender tones",
  },
  {
    id: "monochrome",
    name: "Monochrome",
    branch: "#374151",
    branchDark: "#1f2937",
    leaf: "#9ca3af",
    background: "#f9fafb",
    description: "Classic black and white",
  },
  {
    id: "neon",
    name: "Neon",
    branch: "#0891b2",
    branchDark: "#0e7490",
    leaf: "#22d3ee",
    background: "#0a0e27",
    description: "Bright neon cyan",
  },
  {
    id: "fire",
    name: "Fire",
    branch: "#dc2626",
    branchDark: "#991b1b",
    leaf: "#fef08a",
    background: "#1a0505",
    description: "Hot fire colors",
  },
  {
    id: "ocean",
    name: "Ocean Deep",
    branch: "#0c4a6e",
    branchDark: "#075985",
    leaf: "#7dd3fc",
    background: "#f0f9ff",
    description: "Deep ocean blues",
  },
  {
    id: "high-contrast",
    name: "High Contrast",
    branch: "#000000",
    branchDark: "#1f2937",
    leaf: "#fbbf24",
    background: "#ffffff",
    description: "Maximum visibility",
  },
];

export function getPaletteById(id: string): ColorPalette {
  return colorPalettes.find((p) => p.id === id) || colorPalettes[0];
}
